seo_job/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url

from seo_job.views import JobList, JobDetail


app_name = 'seo_job'
urlpatterns = [
    url(r'^$', JobList.as_view(), name='job_list'),
    url(r'^(?P<pk>\d+)/$',
        JobDetail.as_view(), name='job_detail')
]

seo_post/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url

from seo_post.views import PostList, PostDetail


app_name = 'seo_post'
urlpatterns = [
    url(r'^category/(?P<category_slug>[\w-]+)/$', PostList.as_view(),
        name='post_list_by_category'),
    url(r'^(?P<post_type>[\w-]+)/$', PostList.as_view(),
        name='post_list_by_type'),
    url(r'^$', PostList.as_view(), name='post_list'),
    url(r'^(?P<post_type>[\w-]+)/(?P<slug>[\w-]+)/$',
        PostDetail.as_view(), name='post_detail')
]

seolondon/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView
from django.views.static import serve

admin.autodiscover()

urlpatterns = [
    url(r'^sitemap\.xml$', sitemap,
        {'sitemaps': {'cmspages': CMSSitemap}}),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^filer/', include('filer.urls')),
    url(r'^filebrowser_filer/', include('ckeditor_filebrowser_filer.urls')),
]

urlpatterns += i18n_patterns(
    url(r'^admin/', include(admin.site.urls)),  # NOQA
    url(r'^newsletter/thank_you/',
        TemplateView.as_view(
            template_name='newsletter_thank_you.html'
        ), name='newsletter_thank_you'),
    url(r'^', include('cms.urls')),
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = [
        url(r'^media/(?P<path>.*)$', serve,  # NOQA
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    ] + staticfiles_urlpatterns() + urlpatterns  # NOQA

seo_post/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.core.urlresolvers import reverse
from django.db import models
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible
from django.utils.text import slugify

from ckeditor.fields import RichTextField
from filer.fields.image import FilerImageField

from seo_post.querysets import PostQuerySet


@python_2_unicode_compatible
class PostCategory(models.Model):

    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if self.slug is None:
            self.slug = slugify(self.name)
        super(PostCategory, self).save(*args, **kwargs)


@python_2_unicode_compatible
class Post(models.Model):

    BLOG = 'blog'
    NEWS = 'news'
    POST_TYPES = (
        (BLOG, 'Blog'),
        (NEWS, 'News')
    )

    post_type = models.CharField(
        max_length=20,
        choices=POST_TYPES
    )
    title = models.CharField(
        max_length=60
    )
    subtitle = models.CharField(
        max_length=150,
        blank=True
    )
    slug = models.SlugField(
        max_length=50,
        unique=True
    )
    date_publish = models.DateTimeField(
        default=timezone.datetime.now
    )
    date_expire = models.DateTimeField(
        null=True,
        blank=True
    )
    categories = models.ManyToManyField(
        PostCategory,
        blank=True,
        related_name='posts'
    )
    body = RichTextField(
        config_name='seopost_ckeditor'
    )
    excerpt = models.TextField(
        blank=True
    )
    main_image = FilerImageField(
        null=True,
        blank=True,
        related_name='+',
        on_delete=models.SET_NULL
    )
    listing_image = FilerImageField(
        null=True,
        blank=True,
        related_name='+',
        on_delete=models.SET_NULL
    )
    author = models.CharField(
        max_length=100,
        default='SEO London'
    )
    author_image = FilerImageField(
        null=True,
        blank=True,
        related_name='+',
        on_delete=models.SET_NULL
    )
    is_public = models.BooleanField(default=False)

    objects = PostQuerySet.as_manager()

    # TODO: add view counts somewhere

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if self.slug is None:
            self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
            'seo_post:post_detail',
            kwargs={'post_type': self.post_type, 'slug': self.slug}
        )

seo_post/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals


from django.views import generic
from seo_post.models import Post, PostCategory


class PostList(generic.ListView):

    model = Post
    paginate_by = 14

    def get_queryset(self):
        qs = super(PostList, self).get_queryset()
        if 'post_type' in self.kwargs:
            qs = qs.filter(post_type=self.kwargs['post_type'])
        if 'category_slug' in self.kwargs:
            qs = qs.filter(categories__slug=self.kwargs['category_slug'])
        return qs.published().order_by('-date_publish')

    def get_context_data(self, **kwargs):
        if self.kwargs.get('category_slug', None):
            kwargs['category'] = \
                PostCategory.objects.filter(
                    slug=self.kwargs['category_slug']
                ).first()
        return super(PostList, self).get_context_data(**kwargs)


class PostDetail(generic.DetailView):

    model = Post

    def get_queryset(self):
        qs = super(PostDetail, self).get_queryset()
        return qs.published()

seo_post/templates/seo_post/post_detail.html
{% extends "base.html" %}
{% load aws_static_url_tags %}
{% load cms_tags %}
{% load seo_post_tags %}
{% load social_sharing_tags %}
{% load thumbnail %}

{% block "head__social_cards" %}

    {% with meta_description_default="Read '"|add:post.title|add:"' in SEO London" %}
        <meta name="twitter:card" content="summary_large_image">
        <meta name="twitter:site" content="@SEOLondonInfo">
        <meta name="twitter:creator" content="@SEOLondonInfo">
        <meta name="twitter:title" content="{{ post.title }}">
        <meta name="twitter:description" content="{{ post.excerpt|default:meta_description_default }}">
        {% if post.main_image %}
            <meta name="twitter:image" content="{{ post.main_image.url }}" />
        {% else %}
            <meta name="twitter:image" content="{% aws_static_url "Social_Media_Card1_rkwzom.png" %}" />
        {% endif %}

        <meta property="og:url" content="{{ request.scheme }}://{{ request.get_host }}{{ request.path }}" />
        <meta property="og:type" content="article" />
        <meta property="og:title" content="{{ post.title }}" />
        <meta property="og:description" content="{{ post.excerpt|default:meta_description_default }}" />
        {% if post.main_image %}
            <meta property="og:image" content="{{ post.main_image.url }}" />
        {% else %}
            <meta property="og:image" content="{% aws_static_url "Social_Media_Card1_rkwzom.png" %}" />
        {% endif %}
   {% endwith %}

{% endblock "head__social_cards" %}


{% block header_logo %}
    {% static_placeholder 'blog_news_logo' %}
{% endblock header_logo %}

{% block content %}
    {% with header_color=post.post_type|get_header_color %}
        <div class="ui section">
            <div class="ui container">
                <div class="ui centered grid">
                    <div class="row">
                        <div class="fourteen wide mobile fourteen wide tablet twelve wide computer column segment ">
                            <article>
                                <div class="ui content">
                                    <h1 class="caps-title ui {{ header_color }}">{{ post.title }}</h1>
                                    {% if post.subtitle %}
                                        <div>
                                            {{ post.subtitle }}
                                        </div>
                                    {% endif %}
                                </div>
                                <div class="ui {{ header_color }} divider"></div>
                                {% if post.post_type == 'blog' and post.author_image %}
                                    <img class="ui image left floated circular" src="{% thumbnail post.author_image 100x100 crop=True upscale=True %}">
                                {% endif %}
                                <div>
                                    <div class="ui container">
                                        <div style="padding-bottom:10px;">
                                            <div class="{{ header_color }} "> by {{ post.author }}</div>
                                            <div class="{{ header_color }} "> {{ post.date_publish|date:'d M Y' }} </div>
                                        </div>

                                        <div>
                                            {% for category in post.categories.all %}
                                                <a class="ui basic grey label" href="{% url 'seo_post:post_list_by_category' category_slug=category.slug  %}">{{ category.name }}</a>
                                            {% endfor %}
                                            <a class="ui basic grey label" href="{% url 'seo_post:post_list_by_type' post_type=post.post_type  %}">
                                                All {{ post.post_type|title }}{% if post.post_type != 'news' %}s{% endif %}
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                {% if post.main_image %}
                                    <img class="ui fluid image post-detail__main-image" src="{% thumbnail post.main_image 600x200 crop=True %}">
                                {% endif %}
                                <div class="ui divider"></div>
                                <div class="ui content post-detail__content">
                                    {{ post.body|safe }}
                                </div>
                            </article>
                        </div>
                    </div>
                    <div class="row">
                        <div class="fourteen wide mobile fourteen wide tablet twelve wide computer column segment ">
                            <div class="post-detail__social-sharing">
                                {% social_sharing url=request.build_absolute_uri title=post.title extra_icon_css=header_color %}
                            </div>
                            <div class="ui divider"></div>
                            <div>
                                If you are a candidate, sponsor firm employee, alumni or supporter and you would like to
                                blog for us, please contact us at <a href="mailto:info@seo-london.org">info@seo-london.org</a>
                                expressing your interest.
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endwith %}
{% endblock content %}

seo_post/templates/seo_post/post_list.html
{% extends "base.html" %}
{% load cms_tags %}
{% load seo_post_tags %}
{% load thumbnail %}


{% block header_logo %}
    {% static_placeholder 'blog_news_logo' %}
{% endblock header_logo %}


{% block content %}
    {% with header_color=view.kwargs.post_type|get_header_color %}
        <div class="ui section">
            <div class="ui centered relaxed grid container">
                {# Main Post List #}
                <div class="sixteen wide mobile sixteen wide tablet ten wide computer column">
                    <h1 class="post-list__main-header__post-type caps-title {{ header_color }} ">
                        {% if view.kwargs.post_type == 'blog' %}
                            Blog
                        {% elif view.kwargs.post_type == 'news' %}
                            News
                        {% else %}
                            Blog / News
                        {% endif %}
                    </h1>
                    {% if category %}
                        <h2 class="post-list__main-header__category {{ header_color }}">
                            {{ category.name }}
                        </h2>
                    {% endif %}
                    <div class="ui {{ header_color }} divider"></div>
                    <div class="ui section">
                        {% include 'seo_post/_include/_list_item_list.html' with page_obj=page_obj header_color=header_color only %}
                        <div class="ui {{ header_color }} divider"></div>
                        <div>
                            {% include "seo_post/_include/pagination.html" with page_obj=page_obj only %}
                        </div>
                    </div>
                </div>
                {# TAGS #}
                <div class="sixteen wide mobile sixteen wide tablet four wide computer column ">
                    <h2 class="caps-title ui {{ header_color }}">
                        Tags
                    </h2>
                    <div class="ui {{ header_color }} divider"></div>
                    <div class="ui section">
                        {% get_post_categories as categories %}
                        <ul class="ui list">
                            {% for category in categories %}
                                <li>
                                    {% if view.kwargs.category_slug == category.slug %}
                                        {{ category.name }}
                                    {% else %}
                                        <a href="{% url 'seo_post:post_list_by_category' category_slug=category.slug  %}">
                                            {{ category.name }}
                                        </a>
                                    {% endif %}
                                </li>
                            {% endfor %}
                            {% get_post_types as post_types %}
                            {% for post_type in post_types %}
                                {% if view.kwargs.post_type != post_type %}
                                    <li>
                                        <a href="{% url 'seo_post:post_list_by_type' post_type=post_type  %}">
                                            {{ post_type|title }}{% if post_type != 'news' %}s{% endif %}
                                        </a>
                                    </li>
                                {% endif %}
                            {% endfor %}
                            <li>
                                <a href="{% url 'seo_post:post_list' %}">
                                    All
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                {# INTEREST #}
                <div class="sixteen wide mobile sixteen wide tablet fourteen wide computer column ">
                    <div>
                        If you are a candidate, sponsor firm employee, alumni or supporter and you would like to
                        blog for us, please contact us at <a href="mailto:info@seo-london.org">info@seo-london.org</a>
                        expressing your interest.
                    </div>
                </div>
            </div>
        </div>
    {% endwith %}
{% endblock content %}