seo_job/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url

from seo_job.views import JobList, JobDetail


app_name = 'seo_job'
urlpatterns = [
    url(r'^$', JobList.as_view(), name='job_list'),
    url(r'^(?P<pk>\d+)/$',
        JobDetail.as_view(), name='job_detail')
]

seolondon/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView
from django.views.static import serve

admin.autodiscover()

urlpatterns = [
    url(r'^sitemap\.xml$', sitemap,
        {'sitemaps': {'cmspages': CMSSitemap}}),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^filer/', include('filer.urls')),
    url(r'^filebrowser_filer/', include('ckeditor_filebrowser_filer.urls')),
]

urlpatterns += i18n_patterns(
    url(r'^admin/', include(admin.site.urls)),  # NOQA
    url(r'^newsletter/thank_you/',
        TemplateView.as_view(
            template_name='newsletter_thank_you.html'
        ), name='newsletter_thank_you'),
    url(r'^', include('cms.urls')),
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = [
        url(r'^media/(?P<path>.*)$', serve,  # NOQA
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    ] + staticfiles_urlpatterns() + urlpatterns  # NOQA

djangocms_repeater/models.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.db import models
from django.utils.text import slugify

from filer.fields.image import FilerImageField

from cms.models import CMSPlugin


BUTTONCOLOURCHOICE = (
    ('teal', 'Teal'),
    ('orange', 'Orange'),
    ('red', 'Red'),
    ('blue', 'Blue'),
)

BUTTONTYPECHOICE = (
    ('d', 'Donate'),
    ('a', 'Apply Now'),
    ('l', 'Log in'),
    ('n', 'None')
)

HEADERCOLOURCHOICE = (
    ('W', 'White'),
    ('T', 'Teal'),
    ('O', 'Orange'),
    ('R', 'Red'),
)

HEADERALIGNMENTCHOICE = (
    ('L', 'Left'),
    ('C', 'Center'),
    ('R', 'Right'),
)

CAREERSTEPCHOICE = (
    ('b', 'Blue'),
    ('o', 'Orange'),
    ('w', 'White'),
)


_DEFAULT_IMAGE_URL = '{}{}'.format(
    settings.AWS_STATIC_URL, 'placeholder_aewrin.png')


class Repeater(CMSPlugin):
    repeater_name = models.CharField(max_length=50)
    add_columns = models.BooleanField(default=False)

    def __str__(self):
        return self.repeater_name


class CareerStep(CMSPlugin):
    number = models.CharField(max_length=5, default='0')
    title = models.CharField(max_length=50, default='Step')
    description = models.CharField(max_length=300, default='', blank=True)
    style = models.CharField(max_length=1, choices=CAREERSTEPCHOICE,
                             default='w')

    def __str__(self):
        return self.title


class Logo(CMSPlugin):

    LOGO_CHOICES = (
        ('0', 'SEO London'),
        ('1', 'SEO Careers'),
        ('2', 'SEO Scholars'),
        ('3', 'SEO Connect'),
        ('4', 'SEO Schools'),
        ('5', 'SEO Advance'),
    )
    LOGO_IMAGE_URL = {
        '0': 'logos/logo-seo-london.png',
        '1': 'logos/logo-seo-careers.png',
        '2': 'logos/logo-seo-scholars.png',
        '3': 'logos/logo-seo-connect.png',
        '4': 'logos/logo-seo-schools.png',
        '5': 'logos/logo-seo-advance.png',
    }

    logoChoice = models.CharField(
        max_length=1, choices=LOGO_CHOICES, default='0'
    )

    def __str__(self):
        return self.logoChoice

    def image_url(self):
        return self.LOGO_IMAGE_URL.get(
            self.logoChoice,
            self.LOGO_IMAGE_URL.get('0', '')
        )


class SuccessStory(CMSPlugin):
    storyId = models.CharField(max_length=10, default='Story ID')
    name = models.CharField(max_length=50, default='Candidate Name')
    excerpt = models.CharField(max_length=500, default='Excerpt')
    story_image_url = models.URLField(
        max_length=200,
        blank='True',
        default=_DEFAULT_IMAGE_URL)
    story_image = FilerImageField(null=True, blank=True)

    def __str__(self):
        return self.name


class TeamMember(CMSPlugin):
    name = models.CharField(max_length=200, default='Name')
    title = models.CharField(max_length=400, default='Job Title')
    image_url = models.URLField(
        max_length=200,
        blank='True',
        default=_DEFAULT_IMAGE_URL)
    image = FilerImageField(null=True, blank=True)

    def __str__(self):
        return self.title


class Question(CMSPlugin):
    questionText = models.CharField(max_length=10000, default='Question')

    def __str__(self):
        return self.questionText


class SingleHeader(CMSPlugin):
    quoteText = models.CharField(max_length=150, default='Placeholder')
    captionText = models.CharField(max_length=200, default='', blank=True)
    background_image_url = models.URLField(
        max_length=200,
        blank='True',
        default=_DEFAULT_IMAGE_URL)
    background_image = FilerImageField(null=True, blank=True)
    colour = models.CharField(max_length=1, choices=HEADERCOLOURCHOICE, default='W')
    alignment = models.CharField(max_length=1, choices=HEADERALIGNMENTCHOICE, default='L')

    def __str__(self):
        return self.quoteText


class MultipleHeader(CMSPlugin):
    header_name = models.CharField(max_length=100, default='Slider')

    def __str__(self):
        return self.header_name


class MultipleSingleHeader(CMSPlugin):
    quoteText = models.CharField(max_length=150, default='Placeholder')
    captionText = models.CharField(max_length=200, default='', blank=True)
    background_image_url = models.URLField(
        max_length=200,
        blank='True',
        default=_DEFAULT_IMAGE_URL)
    background_image = FilerImageField(null=True, blank=True)
    colour = models.CharField(max_length=1, choices=HEADERCOLOURCHOICE, default='W')
    alignment = models.CharField(max_length=1, choices=HEADERALIGNMENTCHOICE, default='L')

    def __str__(self):
        return self.quoteText


class Button(CMSPlugin):
    buttonText = models.CharField(max_length=100, default='Button Text')
    buttonURL = models.CharField(blank=True, default="/", max_length=100)
    specialButton = models.CharField(max_length=1, choices=BUTTONTYPECHOICE, default='n')
    buttonColour = models.CharField(max_length=10, choices=BUTTONCOLOURCHOICE, default='blue')

    def __str__(self):
        return self.buttenText


class Career(CMSPlugin):
    name = models.CharField(max_length=100, default='Career Name')
    careerURL = models.CharField(blank=True, default="/", max_length=100)

    def __str__(self):
        return self.name

djangocms_repeater/views.py
from django.shortcuts import render

# Create your views here.

djangocms_repeater/templates/button.html
{% if instance.specialButton == "d" %}
<button class="ui {{instance.buttonColour}} donate donate-modal button">{{instance.buttonText}}</button>
{% endif %}
{% if instance.specialButton == "l" %}
<button class="ui {{instance.buttonColour}} log-in button">{{instance.buttonText}}</button>
{% endif %}
{% if instance.specialButton == "a" %}
<button class="ui {{instance.buttonColour}} apply-button button">{{instance.buttonText}}</button>
{% endif %}
{% if instance.specialButton == "n" %}
<a href="{{instance.buttonURL}}" class="ui {{instance.buttonColour}} button">{{instance.buttonText}}</a>
{% endif %}

djangocms_repeater/templates/career.html
{% load cms_tags %}
<a href="{{ instance.careerURL }}" class="card">
    <div class="image">
        {% for plugin in instance.child_plugin_instances %}
        {% render_plugin plugin %}
        {% endfor %}
    </div>
    <div class="content">
        <span class="header">{{ instance.name }}</span>
    </div>
</a>

djangocms_repeater/templates/career_step.html
{% if instance.description %}
    <div class="column {% if instance.style == "b" %} inverted {% endif %} {% if instance.style == "o" %} inverted orangey {% endif %}">
        <div class="support">
            <div class="support-item">
                <div class="number">{{ instance.number }}</div>
                <span>{{ instance.title }}</span>
            </div>
            <p>{{ instance.description }}</p>
        </div>
    </div>
{% else %}
<div class="column training-item">
    <div class="number">{{ instance.number }}</div>
    <span>{{ instance.title }}</span>
</div>
{% endif %}

djangocms_repeater/templates/logo.html
{% load aws_static_url_tags %}

<div class="logo item">
    <a href="/"><img src="{% aws_static_url instance.image_url %}" alt="Logo image for {{ instance.get_logoChoice_display }}"></a>
</div>

djangocms_repeater/templates/multiple-header.html
<div class="slider">
    <ul>

        {% load cms_tags %}

        {% for plugin in instance.child_plugin_instances %}

        {% render_plugin plugin %}

        {% endfor %}

    </ul>
</div>

djangocms_repeater/templates/multiple-single-header.html
{% load cms_tags %}
<li class="masthead careers-page" style="background-image:url('{% firstof instance.background_image.url instance.background_image_url %}')">
    <div class="ui grid container middle aligned">
        <div class="sixteen wide mobile sixteen wide tablet eight wide computer column">
            <h1 class="white">
                {{ instance.quoteText }}
            </h1>
            {% if instance.captionText %}
            <h2 class="caption">
                {{ instance.captionText }}
            </h2>
            {% endif %}
            {% for plugin in instance.child_plugin_instances %}
            {% render_plugin plugin %}
            {% endfor %}
        </div>
    </div>
</li>

djangocms_repeater/templates/question.html
{% load cms_tags %}

<div class="title">
    <i class="dropdown icon"></i>
    {{ instance.questionText }}
</div>
<div class="content">
    {% for plugin in instance.child_plugin_instances %}

        {% render_plugin plugin %}

    {% endfor %}
</div>

djangocms_repeater/templates/single-header.html
{% load cms_tags %}
<div class="masthead" style="background-image:url('{% firstof instance.background_image.url instance.background_image_url %}')">
    <div class="ui grid container middle aligned">
        <div class="sixteen wide mobile sixteen wide tablet eight wide computer column">
            <h1 class="white">
                {{ instance.quoteText }}
            </h1>
            {% if instance.captionText %}
            <h2 class="caption">
                {{ instance.captionText }}
            </h2>
            {% endif %}
            {% for plugin in instance.child_plugin_instances %}
                {% render_plugin plugin %}
            {% endfor %}
        </div>
    </div>
</div>

djangocms_repeater/templates/success_story.html
{% load cms_tags %}

<div class="column story" style="background-image:url('{% firstof instance.story_image.url instance.story_image_url %}')">
    <div class="content">
        <h2>{{ instance.name }}</h2>
        <p>{{ instance.excerpt }}</p>
        <a data-story="{{ instance.storyId }}" class="ui success story orange button">Full Story</a>
    </div>
</div>

<div class="ui success story modal {{ instance.storyId }}">
    <div class="header">{{ instance.name }}</div>
    <div class="content">
        <img src="{% firstof instance.story_image.url instance.story_image_url %}" alt="{{ instance.name }} Story">
        {% for plugin in instance.child_plugin_instances %}
        {% render_plugin plugin %}
        {% endfor %}
    </div>
</div>

djangocms_repeater/templates/team_member.html
{% load cms_tags %}
<div class="column team" style="background-image:url('{% firstof instance.image.url instance.image_url %}')">
    <div class="content">
    	<div class="content-wrapper">
        	<h3>{{ instance.name }}</h3>
        	<p>{{ instance.title }}</p>
        </div>	
    </div>
    <div class="overlay">
        {% for plugin in instance.child_plugin_instances %}
        	{% render_plugin plugin %}
        {% endfor %}
    </div>
</div>